#!/usr/bin/env python3
"""Generate synthetic CCSF dispersion data for the fitting demo.

Minimizes the 120-degree ground state once, freezes it, then samples the
three magnon branches at a set of in-plane Q-points and adds Gaussian noise.
The frozen spin directions are printed so the fit config can reuse the SAME
fixed structure (minimization off) -- this makes the demo deterministic and
lets the fit vary only the exchanges J1, J2 against a consistent structure.

    python3 make_fit_data.py
"""
import sys, os
import numpy as np
import yaml

MC = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
sys.path.insert(0, MC)
import magcalc as mc
from magcalc.generic_model import GenericSpinModel
from magcalc.runner import compute_b_matrix


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    cfg = yaml.safe_load(open(os.path.join(here, "config_ccsf.yaml")))
    sm = GenericSpinModel(cfg, base_path=here)
    B = compute_b_matrix(sm)
    p = [cfg["parameters"][k] for k in ["Dp", "Dz", "J1", "J2", "H_mag", "H_dir"]]

    # Minimize the classical 120-degree ground state once (serial: robust).
    calc0 = mc.MagCalc(spin_model_module=sm, spin_magnitude=0.5,
                       hamiltonian_params=p, cache_file_base="ccsf_gen_min",
                       cache_mode="none", initialize=False)
    res = calc0.minimize_energy(method="TNC", num_starts=300, n_workers=1,
                                early_stopping=20, seed=0)
    th, ph = res.x[0::2], res.x[1::2]
    dirs = np.array([[np.sin(t) * np.cos(f), np.sin(t) * np.sin(f), np.cos(t)]
                     for t, f in zip(th, ph)])
    print(f"minimized energy = {res.fun:.4f} meV")
    print("frozen spin directions (paste into the fit config's magnetic_structure):")
    for d in dirs:
        print(f"    - [{d[0]:+.6f}, {d[1]:+.6f}, {d[2]:+.6f}]")

    # Freeze the structure and build the calculator used to synthesize data.
    sm.set_magnetic_structure(th, ph)
    calc = mc.MagCalc(spin_model_module=sm, spin_magnitude=0.5,
                      hamiltonian_params=p, cache_file_base="ccsf_gen",
                      cache_mode="none")

    # Sample the three branches along a few in-plane directions.
    hs = np.linspace(0.08, 0.48, 11)
    hkl = np.vstack([np.c_[hs, hs, 0 * hs],
                     np.c_[hs, 0 * hs, 0 * hs],
                     np.c_[hs, -hs, 0 * hs]])
    E = np.real(np.asarray(calc.calculate_dispersion(hkl @ B, serial=True).energies))
    rng = np.random.default_rng(4)
    rows = [[*hkl[i], E[i, b] + rng.normal(0, 0.05), 0.10, b + 1]
            for i in range(len(hkl)) for b in (0, 4, 8)]
    rows = np.array(rows)
    out = os.path.join(here, "ccsf_disp_synth.csv")
    np.savetxt(out, rows, delimiter=",",
               header="h,k,l,E,sigma,mode  (synthetic: J1=13.3, J2=-0.24, "
                      "Dp=0.566, Dz=-1.94; frozen 120-deg ground state)")
    print(f"wrote {len(rows)} points to {os.path.basename(out)}; "
          f"E {rows[:,3].min():.2f}-{rows[:,3].max():.2f} meV")

    # Save the frozen directions to a YAML fragment for the fit config.
    frag = {"magnetic_structure": {"enabled": True, "type": "pattern",
                                   "pattern_type": "generic",
                                   "directions": [[float(x) for x in d] for d in dirs]}}
    _clean = yaml.safe_load(open(os.path.join(here, "config_ccsf.yaml")))
    # Emit a self-contained fit config: frozen structure (minimization off),
    # DM fixed (it sets the structure), varying only the exchanges J1, J2.
    fit = {
        "parameter_order": ["Dp", "Dz", "J1", "J2", "H_mag", "H_dir"],
        "parameters": {"Dp": 0.566, "Dz": -1.94, "J1": 10.0, "J2": 0.0,
                       "H_mag": 0, "H_dir": [0, 0, 1]},
        "crystal_structure": _clean["crystal_structure"],
        "interactions": _clean["interactions"],
        "magnetic_structure": frag["magnetic_structure"],
        "tasks": {"minimization": False, "fit": True, "plot_fit": True},
        "fitting": {"type": "dispersion", "data_file": "ccsf_disp_synth.csv",
                    "method": "leastsq", "vary": ["J1", "J2"],
                    "bounds": {"J1": [0.0, 30.0], "J2": [-2.0, 2.0]},
                    "match": "nearest"},
        "output": {"fit_report_filename": "CCSF_fit_report.txt",
                   "fit_params_filename": "CCSF_fit_params.yaml"},
        "plotting": {"fit_plot_filename": "CCSF_fit_comparison.png",
                     "show_plot": False},
    }
    with open(os.path.join(here, "config_ccsf_fit.yaml"), "w") as f:
        f.write("# Auto-generated by make_fit_data.py -- CCSF exchange fit demo.\n")
        f.write("# Frozen 120-deg structure + fixed DM; varies only J1, J2.\n")
        f.write("# Run:  magcalc fit config_ccsf_fit.yaml   (recovers J1=13.3, J2=-0.24)\n")
        yaml.safe_dump(fit, f, sort_keys=False)
    print("wrote config_ccsf_fit.yaml")


if __name__ == "__main__":
    main()
