"""Elastic magnetic structure factor, and the mCIF round trip.

Every check here is an exact identity or an independently-authored file -- no
golden numbers generated by this package. The four identities are the ones the
discovery pipeline's stage 5 relies on (DISCOVERY_WORKFLOW_PLAN.md section 9.4):

1. |F_perp|^2 is invariant under a rigid rotation of the whole structure, so a
   refinement's setting cannot change the intensity it predicts;
2. the coherent/incoherent ratio for two sublattices is analytic, which turns
   the Cs2Cu3SnF12 erratum's error into a unit test;
3. systematic absences come out as exact zeros;
4. read(write(x)) == x for the mCIF exporter.

The moment-basis convention is pinned to a file FullProf itself wrote.
"""
import os

import numpy as np
import pytest

from magcalc import diffraction as dif
from magcalc.mcif import (MOMENT_BASES, cartesian_to_moment, moment_to_cartesian,
                          read_mcif, write_mcif)

HERE = os.path.dirname(os.path.abspath(__file__))


def _rotation(axis, angle):
    axis = np.asarray(axis, dtype=float)
    axis = axis / np.linalg.norm(axis)
    K = np.array([[0, -axis[2], axis[1]], [axis[2], 0, -axis[0]], [-axis[1], axis[0], 0]])
    return np.eye(3) + np.sin(angle) * K + (1 - np.cos(angle)) * (K @ K)


# ------------------------------------------------------------------ reciprocal space
def test_reciprocal_lattice_is_dual():
    A = np.array([[4.0, 0, 0], [-2.0, 3.4641016, 0], [0, 0, 12.0]])   # hexagonal
    B = dif.reciprocal_lattice(A)
    assert np.allclose(B @ A.T, 2 * np.pi * np.eye(3), atol=1e-12)


def test_q_cartesian_gives_the_d_spacing():
    """|Q| = 2 pi / d, checked against the closed form for an orthorhombic cell."""
    A = np.diag([3.0, 4.0, 5.0])
    for hkl in ([1, 0, 0], [0, 2, 0], [1, 1, 1], [2, 0, 3]):
        Q = dif.q_cartesian(hkl, A)[0]
        h, k, l = hkl
        d_inv = np.sqrt((h / 3.0) ** 2 + (k / 4.0) ** 2 + (l / 5.0) ** 2)
        assert np.isclose(np.linalg.norm(Q), 2 * np.pi * d_inv, rtol=1e-12)


# ------------------------------------------------------------------ identity 1
def test_intensity_is_invariant_under_rigid_rotation():
    """Rotating lattice, positions, moments and Q together cannot change |F_perp|^2.

    This is the check that a magnetic structure moved between two settings still
    predicts the same pattern -- section 9.2's single transformation, tested.
    """
    rng = np.random.default_rng(0)
    A = np.array([[5.0, 0, 0], [0.5, 6.0, 0], [-1.0, 0.3, 7.0]])       # triclinic
    frac = rng.random((4, 3))
    moments = rng.normal(size=(4, 3))
    R = _rotation([0.3, -0.7, 0.5], 1.1)

    for hkl in ([1, 0, 0], [1, 1, 0], [0, 1, 2], [2, -1, 1]):
        Q = dif.q_cartesian(hkl, A)[0]
        I0 = dif.magnetic_intensity(Q, frac @ A, moments)
        # the same structure, rigidly rotated
        I1 = dif.magnetic_intensity(R @ Q, frac @ (A @ R.T), moments @ R.T)
        assert np.isclose(I0, I1, rtol=1e-12), hkl


def test_only_the_perpendicular_component_scatters():
    """A moment parallel to Q is invisible; perpendicular to Q it is fully visible."""
    A = np.diag([4.0, 4.0, 4.0])
    Q = dif.q_cartesian([1, 0, 0], A)[0]
    assert dif.magnetic_intensity(Q, [[0, 0, 0]], [[1.0, 0, 0]]) < 1e-24
    assert np.isclose(dif.magnetic_intensity(Q, [[0, 0, 0]], [[0, 1.0, 0]]), 1.0)


# ------------------------------------------------------------------ identity 2
def test_coherent_minus_incoherent_is_the_cross_term():
    """|F1 + F2|^2 - (|F1|^2 + |F2|^2) = 2 Re(F1 . F2*), exactly.

    The Cs2Cu3SnF12 erratum in one line: two sublattices entered as two magnetic
    PHASES lose this term, and it is not small -- see the next test.
    """
    rng = np.random.default_rng(7)
    A = np.diag([6.0, 6.0, 10.0])
    pos = rng.random((6, 3)) @ A
    mom = rng.normal(size=(6, 3))
    groups = ['Cu1'] * 3 + ['Cu2'] * 3
    Q = dif.q_cartesian([1, 1, 2], A)[0]

    F1 = dif.perpendicular(dif.structure_factor(Q, pos[:3], mom[:3]), Q)
    F2 = dif.perpendicular(dif.structure_factor(Q, pos[3:], mom[3:]), Q)
    cross = 2.0 * float(np.real(np.vdot(F1, F2)))

    coh = dif.magnetic_intensity(Q, pos, mom)
    inc = dif.incoherent_intensity(Q, pos, mom, groups)
    assert np.isclose(coh - inc, cross, rtol=1e-12, atol=1e-14)


def test_two_phase_treatment_is_wrong_by_a_factor_of_two_when_in_phase():
    """Two identical sublattices at the same position: |2F|^2 = 4|F|^2, not 2|F|^2.

    The extreme case, and the honest statement of the error's size: a multiphase
    refinement is a factor of two low here, which a scale factor absorbs -- which
    is exactly why it converges and reports a plausible chi^2 while ranking the
    candidates wrongly.
    """
    A = np.diag([5.0, 5.0, 5.0])
    Q = dif.q_cartesian([1, 0, 0], A)[0]
    pos = [[0, 0, 0], [0, 0, 0]]
    mom = [[0, 1.0, 0], [0, 1.0, 0]]
    coh = dif.magnetic_intensity(Q, pos, mom)
    inc = dif.incoherent_intensity(Q, pos, mom, ['a', 'b'])
    assert np.isclose(coh, 4.0)
    assert np.isclose(inc, 2.0)
    assert np.isclose(dif.cross_term_fraction(Q, pos, mom, ['a', 'b']), 0.5)


def test_cross_term_fraction_is_zero_when_the_phases_do_not_interfere():
    """Perpendicular moments on two sublattices: the cross term vanishes identically.

    So a small `cross_fraction` proves nothing about a model -- only a large one
    discriminates. Pinning this stops the check being read backwards.
    """
    A = np.diag([5.0, 5.0, 5.0])
    Q = dif.q_cartesian([0, 0, 1], A)[0]
    pos = [[0, 0, 0], [2.5, 0, 0]]
    mom = [[1.0, 0, 0], [0, 1.0, 0]]
    assert abs(dif.cross_term_fraction(Q, pos, mom, ['a', 'b'])) < 1e-12


# ------------------------------------------------------------------ identity 3
def test_antiferromagnetic_absence_is_exact():
    """A simple AFM: the ferromagnetic reflection is exactly absent.

    Two antiparallel moments at (0,0,0) and (1/2,0,0) of a doubled cell cancel at
    even h and add at odd h -- the textbook magnetic superlattice condition.
    """
    A = np.diag([8.0, 4.0, 4.0])
    pos = np.array([[0, 0, 0], [0.5, 0, 0]]) @ A
    mom = [[0, 0, 1.0], [0, 0, -1.0]]
    for h in (0, 2, 4):
        Q = dif.q_cartesian([h, 0, 0], A)[0]
        assert dif.magnetic_intensity(Q, pos, mom) < 1e-24, h
    for h in (1, 3):
        Q = dif.q_cartesian([h, 0, 0], A)[0]
        assert dif.magnetic_intensity(Q, pos, mom) > 1.0, h


def test_form_factor_falls_off_and_is_the_tabulated_one():
    """f(Q) enters squared, and is `magcalc.form_factors`' own value -- not a copy."""
    from magcalc.form_factors import get_form_factor
    A = np.diag([4.0, 4.0, 4.0])
    Q = dif.q_cartesian([2, 0, 0], A)[0]
    I = dif.magnetic_intensity(Q, [[0, 0, 0]], [[0, 1.0, 0]], ions=['Cu2+'])
    f = get_form_factor('Cu2+', float(np.linalg.norm(Q)), g=2.0)
    assert np.isclose(I, f ** 2, rtol=1e-12)
    assert 0.0 < f < 1.0


# ------------------------------------------------------------------ identity 4 + basis
def test_moment_basis_matches_the_file_fullprof_wrote():
    """FullProf's own mCIF states the modulus of the components it writes.

    Ho2BaNiO5 (FullProf Examples/MagneticStructure-SAnnPrefOr): components
    (-0.1441, 0, -8.9931) in a 7.51426 x 5.73623 x 22.5572 A cell carry
    `_atom_site_moment.spherical_modulus 8.99423`, and the same three numbers
    appear as Rx/Ry/Rz of the PCR's magnetic phase, refined within +/-10 mu_B for
    a Ho3+ ion. So the components are mu_B on UNIT crystal axes.

    Under the 'lattice_vectors' reading the same site carries 202.9 mu_B, which no
    ion can, and its moment direction moves from 0.92 deg off -c to 0.31 deg.
    """
    A = np.diag([7.51426, 5.73623, 22.5572])
    comps = [-0.1441, 0.0, -8.9931]
    m_unit = moment_to_cartesian(comps, A, 'unit_axes')
    assert np.isclose(np.linalg.norm(m_unit), 8.99423, atol=1e-4)

    m_latt = moment_to_cartesian(comps, A, 'lattice_vectors')
    assert np.linalg.norm(m_latt) > 200.0                      # unphysical for Ho3+

    ang = lambda v: np.degrees(np.arccos(abs(v[2]) / np.linalg.norm(v)))
    assert np.isclose(ang(m_unit), 0.918, atol=0.01)
    assert np.isclose(ang(m_latt), 0.306, atol=0.01)


@pytest.mark.parametrize("basis", MOMENT_BASES)
def test_moment_conversion_round_trips(basis):
    A = np.array([[5.0, 0, 0], [-2.5, 4.33, 0], [0.4, -0.2, 11.0]])
    m = np.array([0.3, -1.2, 0.7])
    assert np.allclose(cartesian_to_moment(moment_to_cartesian(m, A, basis), A, basis), m,
                       atol=1e-12)


def test_mcif_write_read_round_trip(tmp_path):
    """write -> read reproduces positions and Cartesian moments exactly.

    The written cell is described by (a, b, c, alpha, beta, gamma), so the reader
    rebuilds it in ITS standard orientation -- a rigid rotation of the input. The
    structure must therefore come back rotated but identical in crystal terms,
    which is checked here by comparing moments in fractional/crystal components
    and the intensities (identity 1) rather than raw Cartesian vectors.
    """
    A = np.array([[5.0, 0, 0], [-2.5, 4.330127, 0], [0.0, 0.0, 11.0]])
    sites = [
        {'label': 'Cu1', 'type': 'Cu2+', 'pos': [0.0, 0.0, 0.0], 'moment': [0.4, 0.1, 0.3]},
        {'label': 'Cu2', 'type': 'Cu2+', 'pos': [0.5, 0.25, 0.1], 'moment': [-0.4, 0.2, -0.3]},
    ]
    path = str(tmp_path / "out.mcif")
    write_mcif(path, A, sites)

    data = read_mcif(path)
    assert len(data['sites']) == 2
    A2 = data['lattice_vectors']
    for s_in, s_out in zip(sites, data['sites']):
        assert np.allclose(s_out['pos'], s_in['pos'], atol=1e-6)
        m_in = cartesian_to_moment(s_in['moment'], A, 'unit_axes')
        m_out = cartesian_to_moment(s_out['moment'], A2, 'unit_axes')
        assert np.allclose(m_in, m_out, atol=1e-5)

    # and the physics that survives any setting change: the intensities
    for hkl in ([1, 0, 0], [1, 1, 0], [0, 0, 2]):
        Q1 = dif.q_cartesian(hkl, A)[0]
        Q2 = dif.q_cartesian(hkl, A2)[0]
        I1 = dif.magnetic_intensity(Q1, np.array([s['pos'] for s in sites]) @ A,
                                    [s['moment'] for s in sites])
        I2 = dif.magnetic_intensity(Q2, np.array([s['pos'] for s in data['sites']]) @ A2,
                                    [s['moment'] for s in data['sites']])
        assert np.isclose(I1, I2, rtol=1e-6), hkl


def test_reading_tbsb_is_unchanged_by_the_basis_fix():
    """The Sunny-validated file is immune to the convention change, and that is WHY
    the bug survived: TbSb's moment is (0, 0, -0.708), along c alone, so the two
    bases differ by a positive scale factor and not at all in direction.
    """
    path = os.path.join(HERE, 'data_TbSb.mcif')
    unit = read_mcif(path, moment_basis='unit_axes')
    latt = read_mcif(path, moment_basis='lattice_vectors')
    assert len(unit['sites']) == len(latt['sites'])
    for a, b in zip(unit['sites'], latt['sites']):
        assert np.allclose(a['pos'], b['pos'])
        assert np.allclose(a['direction'], b['direction'], atol=1e-12)


def test_intensity_ratio_report_normalizes_and_reports_the_cross_term():
    A = np.diag([8.0, 4.0, 4.0])
    pos = np.array([[0, 0, 0], [0.5, 0, 0]]) @ A
    mom = [[0, 0, 1.0], [0, 0, -1.0]]
    rows = dif.intensity_ratio_report([[1, 0, 0], [2, 0, 0], [3, 0, 0]], A, pos, mom,
                                      groups=['a', 'b'])
    assert max(r['I'] for r in rows) == pytest.approx(1.0)
    absent = [r for r in rows if r['hkl'] == [2, 0, 0]][0]
    assert absent['I'] < 1e-20
    # The coherent structure factor vanishes here, but each sublattice alone does
    # not: a two-phase refinement predicts a peak that should not exist at all.
    # That is maximal disagreement, and it is the most diagnostic reflection of
    # the three -- not the least.
    assert absent['I_incoherent'] > 0.0
    assert absent['cross_fraction'] == pytest.approx(-1.0)
    present = [r for r in rows if r['hkl'] == [1, 0, 0]][0]
    assert present['cross_fraction'] == pytest.approx(0.5)   # the phases are opposite
    assert present['d'] == pytest.approx(8.0)


def test_config_to_mcif_round_trip(tmp_path):
    """config -> write_mcif -> read_mcif keeps every direction, on a real config path.

    `config_to_sites` builds the model the way `magcalc run` does, and the CLI
    (`magcalc mcif-out`) is a thin wrapper over it. Worth a test of its own
    because nothing else exercised it: the first version imported a loader that
    does not exist, which every unit test here happily missed.

    The 120-degree kagome structure is the case that would catch a silent
    reordering too -- three moments, pairwise at 120 degrees, so any permutation
    or sign slip shows up in the angles.
    """
    from magcalc.mcif import config_to_sites, write_mcif

    cfg = tmp_path / "kagome.yaml"
    cfg.write_text(
        "crystal_structure:\n"
        "  lattice_parameters: {a: 6.0, b: 6.0, c: 8.0, alpha: 90.0, beta: 90.0,\n"
        "                       gamma: 120.0, space_group: 147}\n"
        "  wyckoff_atoms:\n"
        "  - {label: K, pos: [0.5, 0.0, 0.0], spin_S: 1.0, ion: Cu2+}\n"
        "parameters: {J1: 1.0}\n"
        "parameter_order: [J1]\n"
        "interactions:\n"
        "  symmetry_rules:\n"
        "  - {type: heisenberg, distance: 3.0, value: J1}\n"
        "magnetic_structure:\n"
        "  type: pattern\n"
        "  pattern_type: generic\n"
        "  directions: [[1, 0, 0], [-0.5, 0.8660254, 0], [-0.5, -0.8660254, 0]]\n"
        "tasks: {dispersion: false}\n")

    lattice, sites = config_to_sites(str(cfg))
    assert len(sites) == 3
    assert all(np.isclose(s['moment_magnitude'], 2.0) for s in sites)   # g * S

    out = str(tmp_path / "kagome.mcif")
    write_mcif(out, lattice, sites)
    back = read_mcif(out)
    assert len(back['sites']) == 3

    # every pair of moments is 120 degrees apart, before and after the round trip
    def angles(dirs):
        return sorted(round(float(np.degrees(np.arccos(np.clip(
            np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)), -1, 1)))), 3)
            for i, a in enumerate(dirs) for b in dirs[i + 1:])

    assert angles([s['direction'] for s in sites]) == pytest.approx([120.0] * 3, abs=1e-3)
    assert angles([s['direction'] for s in back['sites']]) == pytest.approx([120.0] * 3,
                                                                           abs=1e-3)
