"""The shipped fitting example must fit a model that is actually right.

`examples/fitting/fit_dispersion.yaml` is the config TUTORIAL.md points at for
`magcalc fit`. Until 2026-08-12 it carried two compounding errors:

  * every exchange bond was listed in ONE direction only. The engine sums
    H = (1/2) sum over ORDERED pairs, so a bond listed once contributes half its
    J -- every energy came out a factor 2 low;
  * it declared no `magnetic_structure`, so with J1, J2 > 0 (AFM here, as in
    SpinW) the spectrum was expanded about the all-parallel state -- a stationary
    MAXIMUM, which still yields real, positive, entirely plausible energies.

`disp_data.txt` had been generated by the engine from that same broken model, so
the example's own check -- "the fit recovers J1 = 1.0, J2 = 0.3" -- passed with
flying colours (1.0002 / 0.2967) while the Hamiltonian was wrong twice over. A
check a wrong answer passes is not a check.

The oracle here is therefore ANALYTIC and external to the engine: the Neel-state
LSWT branch of the rectangular-lattice Heisenberg antiferromagnet,

    w(q) = 2 S sqrt( (J1 + J2)^2 - (J1 cos 2*pi*h + J2 cos 2*pi*k)^2 )

which is also what generates the shipped data (make_synthetic_data.py).
"""
import os
import shutil
import subprocess
import sys

import numpy as np
import pytest
import yaml

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
EXAMPLE = os.path.join(ROOT, "examples", "fitting")
CONFIG = os.path.join(EXAMPLE, "fit_dispersion.yaml")

J1_TRUE, J2_TRUE, S_TRUE = 1.0, 0.3, 1.0


def _analytic(h, k, J1=J1_TRUE, J2=J2_TRUE, s=S_TRUE):
    A = J1 + J2
    B = J1 * np.cos(2 * np.pi * h) + J2 * np.cos(2 * np.pi * k)
    return 2.0 * s * np.sqrt(max(A * A - B * B, 0.0))


def _run(cfg_path, workdir):
    return subprocess.run(
        [sys.executable, "-c",
         "import sys;from magcalc.runner import run_calculation;run_calculation(sys.argv[1])",
         cfg_path],
        cwd=workdir, capture_output=True, text=True)


def test_example_bonds_are_listed_in_both_directions():
    """Half the exchange is the quietest possible error: the spectrum keeps its
    shape and only its scale is wrong, which a free `scale` in a fit absorbs."""
    cfg = yaml.safe_load(open(CONFIG))
    offsets = [tuple(b["rij_offset"]) for b in cfg["interactions"]]
    for off in list(offsets):
        rev = tuple(-c for c in off)
        assert rev in offsets, f"bond {off} has no reverse {rev} in the example"


def test_example_dispersion_matches_the_analytic_neel_branch(tmp_path):
    """The engine, driven by the shipped config at the TRUE parameters, must
    reproduce the analytic branch. Fails if either bug comes back: the
    one-direction listing halves it, the missing structure changes it entirely."""
    shutil.copytree(EXAMPLE, tmp_path / "fit")
    d = tmp_path / "fit"
    cfg = yaml.safe_load(open(d / "fit_dispersion.yaml"))
    cfg["parameters"] = {"J1": J1_TRUE, "J2": J2_TRUE}
    cfg["tasks"] = {"dispersion": True}
    cfg.pop("fitting", None)
    qs = [(0.5, 0.0, 0.0), (0.25, 0.25, 0.0), (0.1, 0.0, 0.0), (0.0, 0.35, 0.0)]
    cfg["q_path"] = {f"P{i}": list(q) for i, q in enumerate(qs)}
    cfg["q_path"]["path"] = [f"P{i}" for i in range(len(qs))]
    cfg["q_path"]["points_per_segment"] = 2
    cfg["plotting"] = {"save_plot": False, "show_plot": False, "plot_structure": False}
    cfg["output"] = {"save_data": True, "disp_data_filename": "d.npz"}
    yaml.safe_dump(cfg, open(d / "run.yaml", "w"))

    proc = _run(str(d / "run.yaml"), str(d))
    assert proc.returncode == 0, proc.stderr[-2000:]

    npz = np.load(d / "d.npz")
    energies, qvec = npz["energies"], npz["q_vectors"]
    a = float(yaml.safe_load(open(d / "fit_dispersion.yaml"))
              ["crystal_structure"]["lattice_parameters"]["a"])

    # q_vectors are Cartesian; the chemical cell is a = b, so h = qx*a/2pi.
    for q, bands in zip(qvec, energies):
        h, k = q[0] * a / (2 * np.pi), q[1] * a / (2 * np.pi)
        want = _analytic(h, k)
        # A magnetic supercell folds bands onto the chemical q_path, so the
        # analytic branch must be PRESENT, not necessarily the lowest.
        assert np.min(np.abs(np.asarray(bands) - want)) < 1e-6, (
            f"q=({h:.3f},{k:.3f}): analytic {want:.6f} not among bands "
            f"{np.round(np.sort(bands), 6)}")


def test_shipped_data_is_the_analytic_dispersion():
    """The data must come from the analytic formula, not from the engine --
    otherwise the fit only proves the engine agrees with itself."""
    data = np.loadtxt(os.path.join(EXAMPLE, "disp_data.txt"), delimiter=",")
    resid = [row[3] - _analytic(row[0], row[1]) for row in data]
    sigma = data[0, 4]
    # Noise is seeded Gaussian at this sigma: every point within 4 sigma, and the
    # spread consistent with sigma (a factor-2 error would blow both).
    assert max(abs(r) for r in resid) < 4 * sigma, f"max residual {max(map(abs, resid))}"
    assert 0.3 * sigma < np.std(resid) < 2.0 * sigma, f"residual std {np.std(resid)}"


@pytest.mark.slow
def test_fit_recovers_the_true_parameters(tmp_path):
    """End to end: `magcalc fit` on the shipped example, from deliberately wrong
    starting values, must land on the true J1 = 1.0, J2 = 0.3."""
    shutil.copytree(EXAMPLE, tmp_path / "fit")
    d = tmp_path / "fit"
    proc = _run(str(d / "fit_dispersion.yaml"), str(d))
    assert proc.returncode == 0, proc.stderr[-2000:]

    best = yaml.safe_load(open(d / "fit_params.yaml"))["best_fit_parameters"]
    # 20 points at sigma = 0.05; the fit quotes ~1-2% uncertainties. 5% is loose
    # enough not to be flaky and tight enough that the old halved-exchange model
    # (which needed J ~ 2x) fails it outright.
    assert abs(best["J1"] - J1_TRUE) < 0.05, best
    assert abs(best["J2"] - J2_TRUE) < 0.05, best
