"""The CCSF fit demo must actually recover the exchanges it was generated from.

`examples/materials/CCSF/` ships a round-trip demo rescued on 2026-08-12 from a
stale copy of this tree, where it was untracked and existed nowhere else:
`make_fit_data.py` synthesizes dispersion data from the frozen 120-degree ground
state at J1 = 13.3, J2 = -0.24 (plus Gaussian noise, sigma = 0.05 meV), and
`magcalc fit config_ccsf_fit.yaml` fits J1, J2 back out of it.

WHAT THIS DOES AND DOES NOT PIN -- read before trusting it as an oracle.

The data was generated BY THIS ENGINE from this same Hamiltonian, so a passing
result says nothing about whether the CCSF Hamiltonian is right. It is a
SELF-CONSISTENCY check on the FITTING machinery: that `magcalc fit` inverts the
engine's own forward model and lands on the generating parameters. That is worth
pinning -- it catches regressions in the fit path, the data reader, the frozen-
structure handling and the parameter plumbing -- but it is not physics
validation, and it must never be cited as one.

`tests/test_fit_example.py` exists because exactly this distinction was missed
once already: `examples/fitting/` shipped for months with every bond listed in
one direction and no magnetic structure, and its own "the fit recovers J1, J2"
check passed with flying colours because the shipped data had been generated
from that same broken model. A check a wrong answer passes is not a check.

Hence the assertion here is against the values that GENERATED the data (13.3,
-0.24, recorded in the CSV header and the config's own header comment), NOT
against the fit output observed when the demo was rescued (13.2860735,
-0.23701742). Asserting the latter would be a self-generated golden number: it
would keep passing if the fitter drifted, because the reference would have
drifted with it.
"""
import os
import shutil
import subprocess
import sys

import pytest
import yaml

HERE = os.path.dirname(__file__)
ROOT = os.path.abspath(os.path.join(HERE, ".."))
EXAMPLE = os.path.join(ROOT, "examples", "materials", "CCSF")

# The values make_fit_data.py used to synthesize ccsf_disp_synth.csv; they are
# recorded in that file's own header line and in config_ccsf_fit.yaml's.
J1_TRUE, J2_TRUE = 13.3, -0.24

# Generous next to the fit's own reported uncertainties (+/-0.009, +/-0.004):
# this is a regression gate on the machinery, not a precision claim, and the
# data carries sigma = 0.05 meV of noise.
J1_TOL, J2_TOL = 0.05, 0.02

NEEDED = ("config_ccsf_fit.yaml", "ccsf_disp_synth.csv")


def _generating_values_are_still_what_this_test_claims():
    """The CSV header is the provenance record; keep the test honest against it."""
    with open(os.path.join(EXAMPLE, "ccsf_disp_synth.csv")) as fh:
        header = fh.readline()
    return f"J1={J1_TRUE}" in header and f"J2={J2_TRUE}" in header


def test_synthetic_data_header_records_the_generating_parameters():
    """Cheap, fast, and it guards the premise of the slow test below.

    If someone regenerates the data at different J's, the round-trip test would
    start comparing against the wrong truth -- and would fail in a way that looks
    like a fitter regression. This fails first, and says why.
    """
    assert os.path.isfile(os.path.join(EXAMPLE, "ccsf_disp_synth.csv"))
    assert _generating_values_are_still_what_this_test_claims(), (
        "ccsf_disp_synth.csv was regenerated with different exchanges than the "
        f"J1={J1_TRUE}, J2={J2_TRUE} this test asserts. Update both, or the "
        "round-trip test is checking against a stale truth.")


@pytest.mark.slow
def test_fit_recovers_the_generating_exchanges(tmp_path):
    """Run the shipped demo end to end and check it lands on the truth.

    Runs in a tmpdir copy: `magcalc fit` writes its report and params next to the
    config, and those two outputs are gitignored precisely so the merge gate does
    not dirty the tree.
    """
    for name in NEEDED:
        src = os.path.join(EXAMPLE, name)
        assert os.path.isfile(src), f"missing {name}; the demo is incomplete"
        shutil.copy(src, tmp_path / name)

    proc = subprocess.run(
        [sys.executable, "-m", "magcalc", "fit", "config_ccsf_fit.yaml"],
        cwd=str(tmp_path), capture_output=True, text=True,
    )
    assert proc.returncode == 0, f"fit failed:\n{proc.stdout[-3000:]}\n{proc.stderr[-3000:]}"

    out = tmp_path / "CCSF_fit_params.yaml"
    assert out.is_file(), f"no fit params written:\n{proc.stdout[-2000:]}"
    best = yaml.safe_load(out.read_text())["best_fit_parameters"]

    assert abs(best["J1"] - J1_TRUE) < J1_TOL, (
        f"J1 came back {best['J1']:.6f}, generated from {J1_TRUE}")
    assert abs(best["J2"] - J2_TRUE) < J2_TOL, (
        f"J2 came back {best['J2']:.6f}, generated from {J2_TRUE}")
