#!/usr/bin/env python3
"""One-off converter: legacy CCSF 6-spin python model -> declarative YAML.

Extracts the exact bond list (Heisenberg J11/J12/J13/J2 and DM vectors) from
spin_model.py symbolically, maps out-of-cell neighbours to (atom, cell offset),
and writes config_ccsf.yaml in the GenericSpinModel format that pyMagCalc
Studio (the web app) can import and render. The DM entries are the absolute
vectors J_ij * D_hat (the legacy Hamiltonian multiplies DM by the local J).

Run from examples/CCSF:  python3 convert_to_declarative.py
"""
import sys, os
import numpy as np
import sympy as sp

HERE = os.path.dirname(os.path.abspath(__file__))
MC = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, MC)
sys.path.insert(0, HERE)
import spin_model as legacy

LABELS = ["Cu2_1", "Cu2_2", "Cu1_1", "Cu2_3", "Cu2_4", "Cu1_2"]
PARAMS = ["J11", "J12", "J13", "J2", "Dy", "Dz"]
VALUES = {"J11": 6.89141591, "J12": 8.1417295, "J13": 11.94012088,
          "J2": 0.21420878, "Dy": 0.15, "Dz": -0.26218775}

# Baked negative-chirality ground state (E = -19.6149 meV at the values above)
TH = [1.57280669, 1.56877137, 1.51638102, 1.57280104, 1.56877714, 1.62522784]
PH = [4.17880377, 2.10235963, 6.01060422, 4.17879820, 2.10235593, 0.27055166]


def main():
    syms = sp.symbols("J11 J12 J13 J2 Dy Dz")
    p = list(syms) + [0.0]                     # H = 0
    Jex, DM = legacy.spin_interactions(p)

    apos = np.array(legacy.atom_pos())
    ouc = np.array(legacy.atom_pos_ouc())
    uc = [np.asarray(v).ravel() for v in legacy.unit_cell()]

    # map each OUC index -> (atom k, offsets n1, n2)
    def locate(j):
        for k in range(len(apos)):
            for n1 in (-1, 0, 1):
                for n2 in (-1, 0, 1):
                    tgt = apos[k] + n1 * uc[0] + n2 * uc[1]
                    if np.linalg.norm(ouc[j] - tgt) < 1e-6:
                        return k, n1, n2
        raise RuntimeError(f"could not locate OUC index {j}")

    heis, dms = [], []
    n = len(apos)
    for i in range(n):
        for j in range(ouc.shape[0]):
            Jij = sp.simplify(Jex[i, j])
            if Jij != 0:
                k, n1, n2 = locate(j)
                heis.append((i, k, n1, n2, str(Jij)))
                Dij = DM[i, j]
                if Dij is not None:
                    Dabs = [sp.simplify(Jij * Dij[c]) for c in range(3)]
                    if any(d != 0 for d in Dabs):
                        dms.append((i, k, n1, n2, [str(d) for d in Dabs]))

    print(f"extracted {len(heis)} Heisenberg and {len(dms)} DM directed entries")

    # fractional positions (orthorhombic cell -> componentwise divide)
    cell = np.array([uc[0], uc[1], uc[2]])
    frac = apos @ np.linalg.inv(cell)
    frac = np.round(frac, 8)

    dirs = [[float(np.sin(t) * np.cos(f)), float(np.sin(t) * np.sin(f)),
             float(np.cos(t))] for t, f in zip(TH, PH)]

    L = []
    A = L.append
    A("# =====================================================================")
    A("# Cs2Cu3SnF12 -- distorted spin-1/2 kagome antiferromagnet")
    A("# Linear spin-wave theory (dispersion + S(Q,w)) with pyMagCalc.")
    A("#")
    A("#   magcalc run examples/CCSF/config_ccsf.yaml")
    A("#")
    A("# CORRECT magnetic structure: monoclinic P2_1/n, coplanar 120-degree,")
    A("# *negative* vector chirality. Six Cu sublattices in the orthorhombic")
    A("# kagome-frame cell; three inequivalent nearest-neighbour exchanges")
    A("# J11, J12, J13; DM vectors are J_ij*(0, Dy, -Dz) + symmetry partners")
    A("# (entered below as absolute vectors, i.e. already multiplied by J_ij).")
    A("# Parameters: variant-B refit of the AMATERAS INS data (see README.md).")
    A("# The 120-degree ground state is supplied via magnetic_structure, so the")
    A("# web app (pyMagCalc Studio) renders it on import and no minimization is")
    A("# needed at run time. This file was generated by convert_to_declarative.py")
    A("# from the legacy spin_model.py and is numerically equivalent to it.")
    A("# =====================================================================")
    A("")
    A("parameter_order: [J11, J12, J13, J2, Dy, Dz]")
    A("parameters:")
    for k in PARAMS:
        A(f"  {k}: {VALUES[k]}")
    A("")
    A("crystal_structure:")
    A("  lattice_vectors:")
    for v in cell:
        A(f"    - [{v[0]:.8f}, {v[1]:.8f}, {v[2]:.8f}]")
    A("  atoms_uc:")
    for lbl, f in zip(LABELS, frac):
        A(f"    - {{ label: {lbl}, pos: [{f[0]:.8f}, {f[1]:.8f}, {f[2]:.8f}], "
          f"spin_S: 0.5, ion: Cu2+ }}")
    A("")
    A("magnetic_structure:")
    A("  enabled: true")
    A("  type: pattern")
    A("  pattern_type: generic   # one direction per spin: the minimized")
    A("                          # negative-chirality 120-degree ground state")
    A("  directions:")
    for d in dirs:
        A(f"    - [{d[0]:+.8f}, {d[1]:+.8f}, {d[2]:+.8f}]")
    A("")
    A("interactions:")
    A("  # Directed entries (both orderings of every bond), extracted 1:1 from")
    A("  # the legacy spin model. rij_offset is the neighbour's cell offset.")
    for i, k, n1, n2, v in heis:
        A(f"  - {{ type: heisenberg, pair: [{LABELS[i]}, {LABELS[k]}], "
          f"rij_offset: [{n1}, {n2}, 0], value: \"{v}\" }}")
    for i, k, n1, n2, dv in dms:
        A(f"  - {{ type: dm, pair: [{LABELS[i]}, {LABELS[k]}], "
          f"rij_offset: [{n1}, {n2}, 0], value: [\"{dv[0]}\", \"{dv[1]}\", \"{dv[2]}\"] }}")
    A("")
    A("tasks:")
    A("  minimization: false      # ground state supplied by magnetic_structure")
    A("  dispersion: true")
    A("  sqw_map: true")
    A("")
    A("q_path:")
    A("  Gamma: [0.0, 0.0, 0.0]")
    A("  X:     [0.5, 0.0, 0.0]")
    A("  M:     [0.5, 0.5, 0.0]")
    A("  Y:     [0.0, 0.5, 0.0]")
    A("  path: [\"Gamma\", \"X\", \"M\", \"Y\", \"Gamma\"]")
    A("  points_per_segment: 100")
    A("")
    A("plotting:")
    A("  save_plot: true")
    A("  show_plot: false")
    A("  plot_structure: true")
    A("  disp_plot_filename: CCSF_disp.png")
    A("  sqw_plot_filename: CCSF_sqw.png")
    A("  energy_limits_disp: [0, 16]")
    A("  energy_limits_sqw: [0, 16]")
    A("  broadening: 0.4")
    A("  broadening_width: 0.4")
    A("  energy_resolution: 0.04")
    A("  disp_title: \"Cs2Cu3SnF12 P2_1/n neg-chirality LSWT dispersion\"")
    A("  sqw_title: \"Cs2Cu3SnF12 S(Q,w)\"")
    A("")
    A("calculation:")
    A("  cache_mode: \"none\"")
    A("")
    A("output:")
    A("  save_data: false")

    out = os.path.join(HERE, "config_ccsf.yaml")
    with open(out, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"wrote {out} ({len(L)} lines)")


if __name__ == "__main__":
    main()
