"""Generate `disp_data.txt` for fit_dispersion.yaml from the ANALYTIC dispersion.

The data is deliberately NOT produced by pyMagCalc. If it were, the fit would only
prove the engine agrees with itself, and a wrong Hamiltonian would sail through --
which is exactly what happened here before 2026-08-12: the shipped data had been
generated by the engine from a config with (a) each exchange bond listed in one
direction only, so every J was half its stated value, and (b) no
`magnetic_structure`, so the spectrum was expanded about the all-parallel state,
which for an antiferromagnet is a stationary MAXIMUM. LSWT about a maximum still
returns real, positive, plausible-looking energies. The fit recovered J1 = 1.0002
and J2 = 0.2967 from that data and looked like a success.

Model: 2-D antiferromagnet on a rectangular lattice, one site per chemical cell,
exchange J1 along a and J2 along b (both AFM, positive = AFM in this engine).
The classical ground state is Neel, k = (1/2, 1/2, 0). Linear spin-wave theory for
H = (1/2) sum_<ij> J_ij S_i.S_j over ordered pairs gives one branch:

    w(q) = 2 S sqrt( (J1 + J2)^2 - (J1 cos 2*pi*h + J2 cos 2*pi*k)^2 )

gapless at q = 0 and at the ordering vector, as a Heisenberg antiferromagnet must
be. `tests/test_fit_example.py` pins the engine to this same formula, so the
example's claim -- "the fit recovers the true values" -- means something.

Usage:  python examples/fitting/make_synthetic_data.py
"""
import os

import numpy as np

J1_TRUE, J2_TRUE, S = 1.0, 0.3, 1.0
SIGMA = 0.05          # per-point uncertainty quoted in the file
SEED = 20260812       # fixed, so the shipped file is reproducible


def omega(h, k, J1=J1_TRUE, J2=J2_TRUE, s=S):
    """Neel-state LSWT branch of the rectangular-lattice Heisenberg AFM."""
    A = J1 + J2
    B = J1 * np.cos(2 * np.pi * h) + J2 * np.cos(2 * np.pi * k)
    return 2.0 * s * np.sqrt(np.maximum(A * A - B * B, 0.0))


def main():
    # Two orthogonal scans: (h,0,0) separates J1, (0,k,0) separates J2.
    scan = np.arange(0.05, 0.5001, 0.05)
    q = [(h, 0.0, 0.0) for h in scan] + [(0.0, k, 0.0) for k in scan]

    rng = np.random.default_rng(SEED)
    rows = []
    for h, k, l in q:
        e = omega(h, k) + rng.normal(0.0, SIGMA)
        rows.append((h, k, l, e, SIGMA))

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "disp_data.txt")
    with open(out, "w") as f:
        f.write(f"# h,k,l,E,sigma  (synthetic, true J1={J1_TRUE} J2={J2_TRUE}, S={S})\n")
        f.write("# Generated by make_synthetic_data.py from the ANALYTIC Neel-AFM\n")
        f.write("# dispersion, not by pyMagCalc -- see that file for why.\n")
        for h, k, l, e, s in rows:
            f.write(f"{h:.5f},{k:.5f},{l:.5f},{e:.5f},{s:.5f}\n")
    print(f"wrote {out} ({len(rows)} points)")


if __name__ == "__main__":
    main()
